feat: add support for map remote home paths
vegaprotocol/vegacapsule pull request #133
Opened 2022-06-09 04:00 UTC by daniel1302

## Background:

We are executing the vegacapsule commands in one place (it is a local computer or maybe a single server, not important now). 

All network configurations are available locally; they are uploaded somewhere and pulled by particular network nodes.
But we do not have any `network runtime` data locally; we do not download gigabytes of data as it makes no sense.
To do something with runtime data, we need to call commands directly on the server.

## Idea behind the `command-runner` job

The `command-runner` job is a job running forever on the server. This job has access to all the network files, and we can use it to call remote commands to the remote locations.

The idea is very simple; once we have a job running on the nomad server, we can use the nomad client(which vegacapsule does) to run any command we want.

Let's say we want to call the `/usr/bin/vega tm unsafe_reset_all --home /some/home` command. 

We can do it with the following command: `nomad alloc exec --task "<some task>" "<allocation id>" /usr/bin/vega tm unsafe_reset_all --home /some/home`

### Some questions I got from people when I was discussing the idea:

- `Why do we not use the network job?` - We have to be able to call the command any time, even if the network node is failing or the network has been stopped intentionally.
- `Why do we not use SSH?` - Vegacapsule does not know anything about SSH. If we add it to Vegacapsule, we must manage additional credentials (ssh key). Moreover, the nomad server may be running somewhere we do not have ssh, e.g., windows, macOS, etc.

### Architecture and simple workflow

To see a simple workflow and high-level architecture of the solution, please analyze the diagram below:

![obraz](https://user-images.githubusercontent.com/1239637/173731107-e338a48c-46ab-4a6a-92f5-78b33f067014.png)

# Related links

- [Stagnet 3 Update PR](https://github.com/vegaprotocol/networks-internal)
- [System tests pipeline using this branch for vegacapsule](https://jenkins.ops.vega.xyz/job/common/job/system-tests/2666/)
- [Followup issue for add cmd runner support to adding/removing nodes](https://github.com/vegaprotocol/vegacapsule/issues/144)

# Manual testing:

```
➜  vegacapsule git:(vegacapsule-128/unsafe-reset-all) ✗ go build -o vegacapsule .

➜  vegacapsule git:(vegacapsule-128/unsafe-reset-all) ✗ ./vegacapsule network bootstrap --config-path ./net_confs/config_command_runner.hcl --fo
rce
2022/06/14 22:36:54 generating network
...
...
2022/06/14 22:46:51 starting network success
2022/06/14 22:46:51 saving network state to the file

➜  vegacapsule git:(vegacapsule-128/unsafe-reset-all) ✗ ./vegacapsule network stop
2022/06/14 22:47:17 stopping network
2022/06/14 22:47:17 Stopped Job: testnet-nodeset-validators-0-validator - dff1ed7c-7c22-967c-91e9-ba13a791c213
2022/06/14 22:47:17 Stopped Job: testnet-nodeset-full-1-full - 9b88b149-f38e-141d-6e68-996803815b07
2022/06/14 22:47:17 Stopped Job: testnet-wallet - 67bf9634-fa81-d987-4b67-69d6c3c2391f
2022/06/14 22:47:17 Stopped Job: ganache-1 - e3de3205-2b9f-9730-5250-161536f46202
2022/06/14 22:47:17 Stopped Job: testnet-faucet - 6a333ba1-cbb2-9f52-dfc0-d3f4870df9c8
2022/06/14 22:47:17 stopping network success

./vegacapsule nodes unsafe-reset-all --remote
2022/06/14 22:49:19 Running unsafe-reset-all on remote cluster 
...
...

2022-06-14T22:49:19.961-0500    INFO    vega/unsafe_reset_all.go:58     Removed file    {"path": "/Users/daniel/.vegacapsule/testnet/vega/node1/state/node/checkpoints/20220615034910-39-ca80811adbd8cd37d4de0cf482a58dfc6d7debad33abec5c8c713bf11d74d5cf.cp"}
2022-06-14T22:49:19.962-0500    INFO    vega/unsafe_reset_all.go:58     Removed file    {"path": "/Users/daniel/.vegacapsule/testnet/vega/node1/state/node/checkpoints/20220615034859-29-85f5a27584dec11b3a487afff9a037e8ff4dc540897e7b77b5b0778eb88ec43d.cp"}
2022-06-14T22:49:19.962-0500    INFO    vega/unsafe_reset_all.go:58     Removed file    {"path": "/Users/daniel/.vegacapsule/testnet/vega/node1/state/node/checkpoints/20220615034829-2-e21633d84927a91471c997a3d57aea4e445d230c4eac3eb1b10715c305232614.cp"}
2022-06-14T22:49:19.962-0500    INFO    vega/unsafe_reset_all.go:58     Removed file    {"path": "/Users/daniel/.vegacapsule/testnet/vega/node1/state/node/checkpoints/20220615034849-20-f313548edfda045006471f3f5d9d6c6979e46f288deee98091724f2a4d2e277c.cp"}
2022-06-14T22:49:19.962-0500    INFO    vega/unsafe_reset_all.go:58     Removed file    {"path": "/Users/daniel/.vegacapsule/testnet/vega/node1/state/node/checkpoints/20220615034839-11-aaf3158bbbb538fc792e6c301b27d9caf747cd4eed6e01a11c9976b643d1a70a.cp"}
2022-06-14T22:49:19.962-0500    INFO    vega/unsafe_reset_all.go:38     Removed checkpoint state        {"path": "/Users/daniel/.vegacapsule/testnet/vega/node1/state/node/checkpoints"}

Running the [/Users/daniel/go/bin/vega tm unsafe_reset_all --home /Users/daniel/.vegacapsule/testnet/tendermint/node1/] command for the"testnet-nodeset-full-1-full" node set
Deprecated: snake_case commands will be replaced by hyphen-case commands in the next major release
I[2022-06-14|22:49:20.011] Removed existing address book                module=main file=/Users/daniel/.vegacapsule/testnet/tendermint/node1/config/addrbook.json
I[2022-06-14|22:49:20.013] Removed all blockchain history               module=main dir=/Users/daniel/.vegacapsule/testnet/tendermint/node1/data
I[2022-06-14|22:49:20.014] Reset private validator file to genesis state module=main keyFile=/Users/daniel/.vegacapsule/testnet/tendermint/node1/config/priv_validator_key.json stateFile=/Users/daniel/.vegacapsule/testnet/tendermint/node1/data/priv_validator_state.json

➜  vegacapsule git:(vegacapsule-128/unsafe-reset-all) ✗ ./vegacapsule network start                  
2022/06/14 22:50:05 starting network
...
...

➜  vegacapsule git:(vegacapsule-128/unsafe-reset-all) ✗ curl --silent localhost:3003/statistics | jq -r '.statistics.blockHeight'
19

➜  vegacapsule git:(vegacapsule-128/unsafe-reset-all) ✗ ./vegacapsule network stop --with-command-runners                    
2022/06/14 22:52:54 stopping network
2022/06/14 22:52:54 Stopped Job: testnet-nodeset-full-1-full-cmd-runner-t - 485a4323-a4b9-e72c-e211-999465cfafc2
2022/06/14 22:52:54 Stopped Job: testnet-nodeset-full-1-full - a47e3131-a825-91a8-5590-bf8ce421f521
2022/06/14 22:52:54 Stopped Job: testnet-faucet - c721cbb7-ca25-6e3b-1162-09bd9c5c7bcc
2022/06/14 22:52:54 Stopped Job: ganache-1 - b5f90d39-5257-1cbe-f302-3815cc223e3d
2022/06/14 22:52:54 Stopped Job: testnet-wallet - 6b5afc4f-914d-9ac2-f34c-40e4769ad367
2022/06/14 22:52:54 Stopped Job: testnet-nodeset-validators-0-validator - a7a8c4f7-2031-9eee-ad70-8c66b094aabe
2022/06/14 22:52:54 Stopped Job: testnet-nodeset-validators-0-validator-cmd-runner-t - bb2a5806-03ce-7127-8fc7-44ec57ee650b
2022/06/14 22:52:54 stopping network success
```

closes: #128

2022-06-27 13:32 UTC, daniel1302 commented on nomad/remote_network_commands.go
> +	dataNodeResetCommand := func(mapping types.NetworkPathsMapping) []string {
This function requires the data-node feature implemented here: https://github.com/vegaprotocol/data-node/pull/721/files

2022-07-11 14:27 UTC, karlem requested changes
Hey @daniel1302, thanks for the PR.
I left couple of comments. A lot of them are just small details. But in general I think it would be good to simplify the jobs filters.

2022-07-14 02:04 UTC, daniel1302 commented on types/types.go
> +	CommandRunnersJobs JobStateMap
Yeah that makes much more sense :)

2022-07-14 02:07 UTC, daniel1302 commented on cmd/network_bootstrap.go
> +		// We want state saved even if the network is started with error
Some of the nodes may start but for example, one node(or post-start) may fail but some of the nodes may be running and we have this information in the `NetworkJobs` structure. If We skip saving the state then we do not know what jobs already started and what not.

We would like to have at least information about command-runners running because if there is for example invalid state on the network we would like to call unsafe-reset-all

2022-07-14 14:21 UTC, daniel1302 commented on cmd/network_bootstrap.go
> +		"Timeout in seconds",
Fixed

2022-07-14 14:31 UTC, daniel1302 commented on cmd/network_bootstrap.go
> +	netBootstrapCmd.PersistentFlags().Uint64Var(&timeout,
Fixed

2022-07-14 14:31 UTC, daniel1302 commented on cmd/network_start.go
> +	netStartCmd.PersistentFlags().Uint64Var(&timeout,
Fixed

2022-07-14 14:59 UTC, daniel1302 commented on cmd/network_bootstrap.go
> +		saveState := func(updatedNetState *state.NetworkState) {
Fixed

2022-07-14 14:59 UTC, daniel1302 commented on cmd/network_bootstrap.go
> +		"Timeout in seconds",
fixed

2022-07-14 15:00 UTC, daniel1302 commented on cmd/network_start.go
> +		saveState := func(updatedNetState *state.NetworkState) {
Fixed

2022-07-14 15:00 UTC, daniel1302 commented on nomad/command_executor.go
> +func (runner *CommandExecutor) filterCommandRunnerAllocations(nodeSets []types.NodeSet) ([]*remoteCommandRunnerDetails, error) {
Fixed

2022-07-14 15:01 UTC, daniel1302 commented on nomad/job_runner.go
> +				return nil, fmt.Errorf("failed to parse command runner template: %w", err)
Fixed

2022-07-14 15:57 UTC, daniel1302 commented on generator/initiate.go
> +		nodeSet.RemoteCommandRunner.NomadJobRaw = rawTemplate.String()
Fixed, thank you :)

2022-07-14 17:49 UTC, daniel1302 commented on nomad/command_executor.go
> +			return fmt.Errorf("the remote command runner is not specified for one or more node sets")
Yeah that makes sense :) Fixed

2022-11-09 13:17 UTC, gordsport commented
Closing as a different solution has been found

2022-11-09 13:17 UTC, closed without merging