feat: incorporate import commands into the vegacapsule
vegaprotocol/vegacapsule pull request #172
Opened 2022-06-26 00:38 UTC by daniel1302

2022-07-11 11:24 UTC, karlem requested changes
Hey @daniel1302, thanks for the PR. I understand that the code works. But I would kindly request some changes. Mostly around the code structure. And being clear about what is being imported.

General takeaways from review:

1. I would be specific about the fact that this import `keys` not `network`
2. Clean up the importer. Separate into multiple files. Have one function per key entity - Ethereum, Vega, Tendermint
3. Maybe extract some Ethereum specifi code into ethereum package
4. Be careful about not hardcoding values all over the place.

2022-07-11 11:24 UTC, karlem commented on importer/genesis.go
> +	for _, nodeSet := range netState.GeneratedServices.NodeSets {
I think you can use`GenerateAndSave` function on the generator. That would save you writing all this code with hardcoded paths etc..

2022-07-11 11:24 UTC, karlem commented on importer/network.go
> +type NodeImportData struct {
I would really call it `NodeKeysData` or `NodeWalletsData`. But it should be obvious we are importing keys related stuff only.

2022-07-11 11:24 UTC, karlem commented on importer/network.go
> +	ethereumKeystorePath := filepath.Join(nodeSet.Vega.HomeDir, "wallets", "ethereum")
These paths can't be hardcoded.. They should be included in the `NodeSet` type from the generation.

2022-07-11 11:24 UTC, karlem commented on importer/network.go
> +	tendermintValidatorKey, err := decodeTendermintPrivateKey(data.TendermintValidatorPrivateKey)
```suggestion
	tendermintValidatorKey, err := decodeBase64TendermintPrivateKey(data.TendermintValidatorPrivateKey)
```

2022-07-11 11:24 UTC, karlem commented on importer/network.go
> +	tendermintNodeKey, err := decodeTendermintPrivateKey(data.TendermintNodePrivateKey)
Same as above

2022-07-11 11:24 UTC, karlem commented on importer/network.go
> +		return nil, fmt.Errorf("failed to decode private tendermint validator key: %w", err)
```suggestion
		return nil, fmt.Errorf("failed to decode private tendermint node key: %w", err)
```

2022-07-11 11:24 UTC, karlem commented on importer/network.go
> +func importNodeData(nodeSet types.NodeSet, data NodeImportData) (*types.NodeSet, error) {
I think it would be worth to separate this function into like 3 different ones.
1. DecodeAndImportTmKeys
2. DecodeAndImportVegaKey
3. DecodeAndImportEthereumKey

I feel the function is too long and a bit messy

2022-07-11 11:24 UTC, karlem commented on importer/wallets.go
> +func importPrivateKeyIntoKeystore(privateKeyHex, passwordFilePath, keystorePath string) (*importedEthereumKeystoreInfo, error) {
I wonder if this function should not be in a Ethereum package? Alongside with all other Eth ones.

2022-07-11 11:24 UTC, karlem commented on importer/network.go
> +	if err := importVegaNodeWallet("vega", importNodeWalletData); err != nil {
I feel like this should be called separately in the functions I have mentioned above. As in one command after another. It makes more sene because the code will be more readable and also  you can get rid of the `importNodeWalletInput` struct.

2022-07-11 11:24 UTC, karlem commented on importer/network.go
> +	NodeIndex                     string `json:"node_index"`
Can you just store as `int` instead?

2022-07-11 11:24 UTC, karlem commented on importer/wallets.go
> +func importVegaNodeWallet(vegaBinary string, data importNodeWalletInput) error {
I would honestly create a separate files for each wallet...

2022-07-12 00:41 UTC, daniel1302 commented on cmd/network_import.go
> +		"network-data-path",
Fixed

2022-07-12 00:41 UTC, daniel1302 commented on cmd/network_import.go
> +			return fmt.Errorf("failed to start network: %w", err)
Fixed

2022-07-12 00:42 UTC, daniel1302 commented on cmd/network_import.go
> +			return fmt.Errorf("the network must be stopped before network data is imported")
Fixed

2022-07-12 00:43 UTC, daniel1302 commented on cmd/network_import.go
> +Required values for each node to import keys to the network:
Fixed

2022-07-12 00:44 UTC, daniel1302 commented on cmd/network.go
> +	networkCmd.AddCommand(netImportCmd)
Moved command to `network keys import`

2022-07-12 00:46 UTC, daniel1302 commented on cmd/network_import.go
> +		"Path to the file, that includes entire network information",
fixed

2022-07-12 00:47 UTC, daniel1302 commented on importer/network.go
> +type NodeImportData struct {
Renamed to the `NodeWalletsData`

2022-07-12 00:50 UTC, daniel1302 commented on importer/network.go
> +	tendermintValidatorKey, err := decodeTendermintPrivateKey(data.TendermintValidatorPrivateKey)
Renamed to `decodeBase64TendermintPrivateKey`

2022-07-12 00:51 UTC, daniel1302 commented on importer/network.go
> +		return nil, fmt.Errorf("failed to decode private tendermint validator key: %w", err)
Fixed

2022-07-12 00:53 UTC, daniel1302 commented on importer/genesis.go
> +	log.Println("...update genesis file for the network finished")
Reworded the log information

2022-07-12 01:39 UTC, daniel1302 commented on importer/wallets.go
> +func importPrivateKeyIntoKeystore(privateKeyHex, passwordFilePath, keystorePath string) (*importedEthereumKeystoreInfo, error) {
Moved it to the Ethereum package

2022-07-12 01:43 UTC, daniel1302 commented on importer/network.go
> +func importNodeData(nodeSet types.NodeSet, data NodeImportData) (*types.NodeSet, error) {
I will refactor it :)

2022-07-12 01:45 UTC, daniel1302 commented on importer/wallets.go
> +func importVegaNodeWallet(vegaBinary string, data importNodeWalletInput) error {
moved it to separated files

2022-07-13 02:29 UTC, daniel1302 commented on importer/network.go
> +func importNodeData(nodeSet types.NodeSet, data NodeImportData) (*types.NodeSet, error) {
I have split it into smaller pieces

2022-07-13 02:33 UTC, daniel1302 commented on importer/network.go
> +	NodeIndex                     string `json:"node_index"`
Fixed

2022-07-13 03:14 UTC, daniel1302 commented on importer/network.go
> +	if err := importVegaNodeWallet("vega", importNodeWalletData); err != nil {
Yeah, that makes much more sense. Refactored

2022-07-13 03:15 UTC, daniel1302 commented on importer/network.go
> +	ethereumKeystorePath := filepath.Join(nodeSet.Vega.HomeDir, "wallets", "ethereum")
Fixed, removed all hardcoded path, and added additional info for `NodeSet.NodeWalletInfo`

2022-07-14 00:51 UTC, daniel1302 commented on importer/genesis.go
> +	for _, nodeSet := range netState.GeneratedServices.NodeSets {
Yeah it makes much more sense :) Updated code

2022-07-18 13:26 UTC, karlem approved these changes

2022-07-20 17:36 UTC, daniel1302 reviewed
Rebased from master, resolved conflicts in the go.mod and changelog :) Waiting for CI, then I am going to merge it

2022-07-20 17:38 UTC, merged