Enable running LiqBot
vegaprotocol/vegacapsule pull request #179
Opened 2022-07-07 21:38 UTC by zale144

Add an example config files, add volumes for pre/post, small improvement

2022-07-11 12:44 UTC, karlem requested changes
Hey @zale144, thanks for the PR. Overal it looks good. Just small changes are required. But you have to publish the bots image.

2022-07-11 12:44 UTC, karlem commented on config/config.go
> +func (p *PStartConfig) absPaths(configDir string) error {
```suggestion
func (p *PStartConfig) setAbsPaths(configDir string) error {
```

2022-07-11 12:44 UTC, karlem commented on config/config.go
> +func (d *DockerConfig) absPaths(configDir string) error {
```suggestion
func (d *DockerConfig) setAbsPaths(configDir string) error {
```

2022-07-11 12:44 UTC, karlem commented on config/config.go
> +				return fmt.Errorf("failed to get absolute file path: %w", err)
```suggestion
				return fmt.Errorf("failed to get absolute file path for %q: %w", d.Volumes[i], err)
```

2022-07-11 12:44 UTC, karlem commented on config/config.go
> +	// Pre start
Nit pick: the comment is not really necessary. It is obvious that we set it for `PreStart`

2022-07-11 12:44 UTC, karlem commented on net_confs/config_bot.hcl
> +      volumes = [
Why do you mount it here? We are not using anything form there no?

2022-07-11 12:44 UTC, karlem commented on net_confs/config_bot.hcl
> +      image = "vegaprotocol/liqbot:local"
You will need to publish this image. This would not work :)

2022-07-11 14:20 UTC, zale144 commented on config/config.go
> +	// Pre start
I was trying to be consistent with the comments above

2022-07-11 14:22 UTC, zale144 commented on net_confs/config_bot.hcl
> +      volumes = [
Ah yes, that's a leftover. I was testing mounting with ganache because I had a lot of trouble with the mounting the volume for the bot, and it was kind of faster to test with ganache

2022-07-11 14:23 UTC, zale144 commented on net_confs/config_bot.hcl
> +      image = "vegaprotocol/liqbot:local"
unless building it locally :) I wasn't sure if I have access. Will try

2022-07-15 01:23 UTC, daniel1302 commented on net_confs/config_bot.hcl
> +      image = "vegaprotocol/liqbot:local"
@zale144 pm me if you want access and I can show you how to publish the image :)

2023-02-01 12:50 UTC, closed without merging